name: Commit CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android environment
        uses: android-actions/setup-android@v3

      - name: Install NDK & CMake
        run: |
          sdkmanager "platforms;android-36" "build-tools;36.1.0" "ndk;28.0.13004108" "cmake;3.31.6"

      - name: Install system dependencies (Ubuntu)
        run: |
          sudo apt update
          sudo apt install extra-cmake-modules gettext

      - name: Init submodules
        run: |
          git config core.filemode false
          git submodule update --init --recursive --jobs 4

      - name: Ensure executable scripts
        run: |
          chmod +x ./prepare_personal_build.sh
          chmod +x ./gradlew

      - name: Prepare personal build sources
        run: |
          ./prepare_personal_build.sh

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build fxDebug APK
        run: ./gradlew :app:assembleFxDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-fx-debug
          path: app/build/outputs/apk/fx/debug/*.apk
